project 'UDMTeacher.xcodeproj'

# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'UDMTeacher' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
pod 'Alamofire'
pod 'XCGLogger', '~> 3.5.3'
pod 'ChameleonFramework/Swift'
pod 'Cosmos', '~> 1.2'
pod 'ReachabilitySwift', '~> 2.4'
  # Pods for UDMTeacher

end
